---
app:
  name: OpenDAX
  domain: gandralf.net
  subdomain: hello-dax
  show_landing: true
render_protect: false
csrfEnabled: false
ssl:
  enabled: true
  email: gandra@gmail.com
updateVersions: false
images:
  peatio: quay.io/openware/peatio:2.6.59
  barong: quay.io/openware/barong:2.6.48
  frontend: quay.io/openware/baseapp:2.6.27
  tower: quay.io/openware/tower:2.6.82
  rango: quay.io/openware/rango:3.1.1
finex:
  enabled: false
  image: quay.io/openware/finex:2.6.39
  license_key: changeme
vendor:
  frontend: git@github.com:openware/baseapp.git
kyc:
  provider: local
  authorization_token: changeme
  sandbox_mode: true
  api_endpoint: https://api.kycaid.com/
vault:
  root_token: s.l9vZ9Xp22fy2TW7zWWP7ZJXz
  peatio_rails_token: s.f1Goi3Twx9e1jxl6itadDfkL
  peatio_crypto_token: s.Wn8u9uunwGwzgZ9TTPyY4uOu
  peatio_upstream_token: s.1jS1TcNmrHlafmGDQFnbv1gp
  peatio_matching_token: s.GouZ4H91frEbHN5zaLph1EKE
  barong_token: s.NHETLbXT5Q8EjgmWTyMIAnYn
  finex_engine_token: s.xgqfnKW6yZXQDvlMM5UsbmUA
database:
  host: db
  adapter: mysql
  port: 3306
  user: root
  password: changeme
storage:
  provider: Google
  bucketName: opendax-barong-docs-bucket
  region: fra1
  endpoint: https://fra1.digitaloceanspaces.com
  accessKey: changeme
  secretKey: changeme
  signatureVersion: '2'
twilio:
  enabled: false
  phone_number: "+15005550000"
  account_sid: changeme
  auth_token: changeme
gaTrackerKey: ''
captcha:
  type: none
  siteKey: changeme
  secretKey: changeme
smtp:
  host: smtp.sendgrid.net
  port: 2525
  user: apikey
  password: changeme
  sender_email: noreply@barong.io
  sender_name: Postmaster
  sender_logo: https://storage.googleapis.com/public_peatio/logo.png
wallets:
  eth:
  - kind: deposit
    address: changeme
    max_balance: 0.0
    secret: changeme
  - kind: hot
    address: changeme
    max_balance: 100.0
    secret: changeme
  - kind: warm
    address: changeme
    max_balance: 1000.0
    secret: changeme
  btc:
  - kind: deposit
    address: changeme
    max_balance: 0.0
  - kind: hot
    address: changeme
    max_balance: 100.0
  - kind: warm
    address: changeme
    max_balance: 1000.0
parity:
  network: testnet
  address: parity
  rpcport: 8545
  port: 30303
bitcoind:
  enabled: false
  rpcuser: admin
  rpcpassword: changeme
  address: bitcoind
  network: testnet
  rpcport: 18332
  port: 18333
litecoind:
  rpcuser: admin
  rpcpassword: changeme
  address: litecoind
  network: testnet
  rpcport: 19332
  port: 19335
terraform:
  credentials: "~/safe/opendax.json"
  project: example-opendax
  region: europe-west4
  zone: europe-west4-a
  instance_name: opendax-cloud
  machine_type: n1-standard-4
  image: debian-cloud/debian-9
